### ISSUE TITLE
Homepage needs easily accessible screenshots 

### ISSUE THREAD

**Issue by sadawson** [kenjitoyama/gleba#4]
Had a call come in about someone else keen to setup the system. 

One think I think that needs to happen is some screenshots of the main parts of the application need to go up and link on the front page needs to go in.

Mike Barrett suggested getting some screenshots up on the wiki so that people can see what it is before downloading its. Its impossible to see it from the code or readme.

Might jump on this a little later if there is some time to do a pull.

**Comment by kenjitoyama** [comment]
Hi,

I'm not sure it's an "issue" of Gleba, so I think this should not be really here. This could be on the wiki instead.

Having said that, I definitely think screenshots would be a great addition. I've thought about that last week, but I haven't had the time to make the default screen visually nice. It's a bit too crowded in some places. The Web version is a bit cleaner and maybe you can put a screenshot of that in the wiki.

I've migrated the GTK GUI to GTK Builder, have a look at that, it's a lot easier to play with it. We can experiment with that instead of messing up the code as we were doing before when it was monolithic.

**Comment by sadawson** [comment]
I got the screenshots for some of the web page functionality just need to get it hosted up somewhere where we can link to view it.

Not sure where is a suitable place to host it.

**Comment by kenjitoyama** [comment]
I think the wiki can hold these images. Try editing the "screenshots" page, I can see a button "image" in the toolbox. I haven't tried it though.

**Comment by sadawson** [comment]
It gives you a dialog to provide a URL for the image you wish to link. There is no upload feature.

**Comment by kenjitoyama** [comment]
I can put them into my personal picasa account. Send them to my personal email, and I'll upload them here, then you can play with the layout.
